### ISSUE TITLE
Doesn't work with simple Hash

### ISSUE THREAD

**Issue by asterite** [MakeNowJust/crustache#1]
This gives a compile error:

``` crystal
require "crustache"

string = "Hello {{name}}"
values = {"name": "Crystal"}

template = Crustache.parse(string)
result = Crustache.render(template, values)
puts result
```

I didn't dig much into your code, but I see you use **lots** of type annotations. And in a language like Crystal, this is usually _bad_. Because type restrictions **restrict** the types you can accept, and then you loose the advantage that duck typing gives you.

Type restrictions should _mostly_ be used for overloading purposes.

**Comment by makenowjust** [comment]
> Type restrictions should mostly be used for overloading purposes.

All right.  Now, I fixed crustache codes to reducing type restrictions.

However, I seemed this issues is other problem.  For example, I have such a code:

``` crystal
tmpl = Crustache.parse "{{#scope}}
  {{value}}
{{/scope}}
"
model = {
  "scope" => [
    { "value" => 1 },
    { "value" => 2 },
  ]
}

puts Crustache.render tmpl, model
```

This code could not run, because `model`'s type is `Hash(String, Array(Hash(String, Int32)))` and crustache's internal stack (it expresses Mustache's context stack `{{#scope}}...{{/scope}}`) type is `Array(Hash(String, Array(Hash(String, Int32))))` but this code may push `Hash(String, Int32)` value into internal stack, so it raises incorrect type error.

So far I solved this problem by using recursion types like JSON.

``` crystal
alias Model = String | Int32 | Array(Model) | Hash(String, Model)

tmpl = Crustache.parse "{{#scope}}
  {{value}}
{{/scope}}
"
model = {
  "scope" => [
    { "value" => 1 } of String => Model,
    { "value" => 2 } of String => Model,
  ] of Model as Model
} of String => Model

puts Crustache.render tmpl, model as Model
```

This solution works right, but `model`'s type and type annotations are more complex than before. So, I had been finding more better solution.

In this morning, I understood a solution!!  Generics type is concrete, so I don't use Generics type for internal stack.  I made my `Context` class and replaced internal stack to this `Context`. e41a453734164dd3337f325a120f11ee1975832e

Now, you can run this code. Thank @asterite.

**Comment by asterite** [comment]
@MakeNowJust Great!! I just tried it and it worked.

Yes, dealing with these types is hard. I was going to suggest to use a wrapper for the model, I think you did that :-)
